# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'JFrog Platform V2'
    command: | 
      jf npmc --repo-resolve alpha-npm-virtual --repo-deploy alpha-npm-virtual
      jf npm install --build-name '$(Build.DefinitionName)' --build-number '$(Build.BuildNumber)'
      jf npm publish --build-name '$(Build.DefinitionName)' --build-number '$(Build.BuildNumber)'
      jf rt bce '$(Build.DefinitionName)' '$(Build.BuildNumber)'
      jf rt bag '$(Build.DefinitionName)' '$(Build.BuildNumber)'
      jf rt bp '$(Build.DefinitionName)' '$(Build.BuildNumber)'
      jf bs '$(Build.DefinitionName)' '$(Build.BuildNumber)'

- task: CmdLine@2
  inputs:
    script: 'sleep 60'

- task: JFrogNpm@1
  inputs:
    command: 'ci'
    artifactoryConnection: 'JFrog Platform V2'
    sourceRepo: 'alpha-npm-virtual'
    collectBuildInfo: true
    threads: '2'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true

- task: JFrogNpm@1
  inputs:
    command: 'pack and publish'
    artifactoryConnection: 'JFrog Platform V2'
    targetRepo: 'alpha-npm-virtual'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true

- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'JFrog Platform V2'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: JFrogBuildScan@1
  inputs:
    xrayConnection: 'JFrog Platform V2'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: false
    vuln: true

      

       


