resources:
  - name: git_node_repo
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: GITHUB_MPATEL
      # Repository path, including org name/repo name
      path: MaharshiPatel/react-node-app                     # Update with your "git_user"/SwampUp2021
      buildOn:
        pullRequestCreate: true
        commit: true
      branches:
        # Specifies which branches will trigger dependent steps
        include: main

  - name: node_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory_MPATEL
      buildName:  'react-node-app'
      buildNumber: $run_number

pipelines:
  - name: react_node_app
    configuration:
      environmentVariables:
        readOnly:
          my_env_var: '1.0.$run_number'
    steps:
      - name: npm_build_step
        type: NpmBuild
        configuration:
          repositoryName: dashboard-npm-virtual                                      # required, npm repository name on artifacctory
          sourceLocation: ./      # required, location of package.json file
          integrations:
            - name:  Artifactory_MPATEL  # required
          inputResources:
            - name: git_node_repo   # required
        execution:
          onSuccess:
            - cd $res_src_resourcePath

      - name: npm_publish_step
        type: NpmPublish
        configuration:
          repositoryName: dashboard-npm-virtual        # required, npm repository name on artifactory
          autoPublishBuildInfo: true       # optional
          forceXrayScan: true              # optional
          failOnScan: false                 # default true
          integrations:
            - name: Artifactory_MPATEL            # required
          inputSteps:
            - name: npm_build_step         # required
          outputResources:
            - name: node_build_info

      - name: xrayScanStep
        type: XrayScan
        configuration:
          inputResources:
            - name: node_build_info

      
