name: 'reactApp'
on:
  push:
    branches:
      - main
  pull_request:
    types: 
      - closed
    branches:
      - main
  workflow_dispatch:

jobs:
 npm-build-and-publish:
   runs-on: ubuntu-latest
   env:
     BUILD_NAME: 'reactApp'
     JFROG_BUILD_STATUS: PASS
   steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: Use Node.js
       uses: actions/setup-node@v4
       with: 
        node-version: "18.15.0"
     - name: JFrog CLI setup 🐸
       uses: jfrog/setup-jfrog-cli@v4
       env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
        JF_USER: ${{secrets.JF_USER}}
        JF_ACCESS_TOKEN: ${{secrets.JF_ACCESS_TOKEN}}
     - name: Health check JFrog Artifactory instance 🐸
       run: |
        jf --version
        jf rt ping
        jf config show
     - name: Build and publish
       run: |
         # Configure the project
         jf npmc --repo-resolve alpha-npm-virtual --repo-deploy alpha-npm-virtual
         # Build the project using JFrog CLI
         jf npm install --build-name ${{env.BUILD_NAME}} --build-number ${{github.run_number}}
         jf npm publish --build-name ${{env.BUILD_NAME}} --build-number ${{github.run_number}}
     - name: Failure check
       run: |
         echo "JFROG_BUILD_STATUS=FAIL" >> $GITHUB_ENV
       if: failure()
     - name: Publish build NPM build-info
       run: |
         # Collect and store environment variables in the build-info
         jf rt bce ${{env.BUILD_NAME}} ${{github.run_number}}
         # Collect and store VCS details in the build-info
         jf rt bag ${{env.BUILD_NAME}} ${{github.run_number}}
         # Publish the build-info to Artifactory
         jf rt bp ${{env.BUILD_NAME}} ${{github.run_number}}
         # Scan the published build-info with Xray
         # jf rt bs
       if: always()
