name: Reusable Docker Build & Push

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      build_number:
        required: true
        type: string
    secrets:
      JF_URL:
        required: true
      JF_USER:
        required: true
      JF_PASSWORD:
        required: true

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: JFrog CLI setup 🐸
        uses: jfrog/setup-jfrog-cli@v4
        env:
         JF_URL: ${{ secrets.JF_URL }}
         JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
         JF_USER: ${{secrets.JF_USER}}

      - name: Login to JFrog Docker Repo
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.JF_URL }}
          username: ${{ secrets.JF_USER }}
          password: ${{ secrets.JF_PASSWORD }}

      - name: Build Docker Image 🐳
        run: |
          jf docker build . -t ${{ secrets.HOST }}/alpha-docker-virtual/${{ inputs.image_name }}:${{ inputs.build_number }}
          

      - name: Push Docker Image to JFrog 🐳
        run: |
          jf docker push ${{ secrets.HOST }}/alpha-docker-virtual/${{ inputs.image_name }}:${{ inputs.build_number }}
        
